# This Dockerfile provides a starting point for a ROCm installation of Tensile.

# Parameters related to building hip

FROM rocm/dev-ubuntu-16.04:2.9
LABEL maintainer="huang.shuang@amd"

USER root
ARG user_uid

# Install dependent packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    rock-dkms \
    rocm_smi64 \
    cmake \
    ca-certificates \
    git \
    pkg-config \
    python3 \
    python3-dev \
    python3-pip \
    python3-pytest \
    python3-setuptools \
    python3-yaml \
    libnuma1 \
    llvm-6.0-dev \
    libboost-all-dev \
    zlib1g-dev \
    libomp-dev \
    vim \
    bash-completion \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install wheel && pip3 install tox pyyaml

ADD ../*.sh ~/


